import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./Providers";

import { ThemeProvider } from "next-themes";
import { Analytics } from "@vercel/analytics/next";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen "dark:bg-black bg-stone-50 transition-colors duration-200`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} storageKey="theme">
          <Analytics />
          
            <Providers>
              <main>
                {children}
              </main>
            </Providers>

        </ThemeProvider>
      </body>
    </html >
  );
}
